bolsa/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
path("", views.index, name="index"),
path("oferta/<int:id>", views.show_oferta, name="oferta"),
path("oferta/new", views.new_oferta,name="new_oferta"),
path("oferta/categoria/<int:id>", views.show_categoria,name="show_categoria"),
path("oferta/<int:id>/borrar", views.borrar_oferta, name="borrar_oferta"),
path("oferta/<int:id>/editar", views.editar_oferta, name="editar_oferta"),
]

proyecto_etapa2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("bolsa.urls")),
    path("cuenta/", include("cuenta.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bolsa/models.py
from django.db import models
from cuenta.models import Perfil, Categoria

# Create your models here.

class Oferta(models.Model):
    titulo = models.CharField(max_length=30)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to="oferta/", null=True)
    oferente = models.ForeignKey(Perfil, on_delete = models.CASCADE,default=None, related_name="oferta_creados")
    fecha_creado = models.DateField(auto_now_add=True)
    fecha_modificado = models.DateField(auto_now=True)
    categoria = models.ForeignKey(Categoria, on_delete = models.SET_NULL,null=True)
    fecha_caducacion =models.DateField(null=True,blank=True,default=None)
    def __str__(self):
        return self.titulo

bolsa/forms.py
from django import forms
from .models import Oferta

class OfertaForm(forms.ModelForm):
    imagen=forms.ImageField(required=False)
    class Meta:
        model = Oferta
        fields = ("titulo", "descripcion","imagen","fecha_caducacion")

class SearchForm(forms.Form):
    titulo = forms.CharField(max_length=30, required = False)
    
    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields["titulo"].widget.attrs["placeholder"] = "Ingrese profesion"
        

bolsa/views.py
from django.shortcuts import render, redirect
from .models import Oferta
from cuenta.models import Categoria
from .forms import OfertaForm,SearchForm
from django.contrib.auth.decorators import login_required
from datetime import datetime
# Create your views here.


def index(request):
    if request.GET:
        search_form = SearchForm(request.GET)
    else:
        search_form = SearchForm()

    filtro_titulo = request.GET.get("titulo", None)
    if filtro_titulo:
        ofertas_buscar = Oferta.objects.filter(oferente__matricula_de_trabajador__titulo__titulo__icontains=filtro_titulo)
    else:   
        ofertas_buscar=None

    if request.user.is_authenticated:
        ofertas1=Oferta.objects.filter(oferente__localidad=request.user.localidad)
    else:
        ofertas1 = None  
    ofertas=Oferta.objects.all()
    contexto = {"ofertas" : ofertas,
                "ofertas1" : ofertas1,
                "ofertas_buscar" : ofertas_buscar,
                "search_form" : search_form
                }
    return render(request, "bolsa/index.html",contexto)

@login_required
def new_oferta(request):
    if request.user.tipo_usuario=="trabajador":
        if request.user.matricula_de_trabajador.all().count()>0:
            if request.method == "POST":
                form= OfertaForm(request.POST,request.FILES)        
                if form.is_valid():
                    datos=form.cleaned_data
                    b=datetime.now()
                    
                    if (datos["fecha_caducacion"] is None) or (datos["fecha_caducacion"] > b.date()):
                        oferta=form.save(commit=False)
                        oferta.oferente = request.user  
                        oferta.categoria_id=request.user.categoria.id
                        oferta.save()
                        return redirect("oferta", oferta.id)
                    else:
                        contexto={"form":form,"error_fecha":"La fecha es vieja"}
                        return render(request, "bolsa/new.html",contexto)        
                else:
                    contexto={"form":form,}
                    return render(request, "bolsa/new.html",contexto)
            #Metodo Get        
            form = OfertaForm()
            contexto={"form":form,}
            return render(request, "bolsa/new.html",contexto)
        else:
            return redirect("cargar_titulo", request.user.id)
    else:
        return redirect("index")

def show_oferta(request,id):

    oferta=Oferta.objects.get(pk=id)
    usuario=oferta.oferente
    contexto = {
    "oferta":oferta,}
    return render(request,"bolsa/oferta.html",contexto)

def show_categoria(request,id):
    if request.GET:
        search_form = SearchForm(request.GET)
    else:
        search_form = SearchForm()

    filtro_titulo = request.GET.get("titulo", None)
    if filtro_titulo:
        ofertas_buscar = Oferta.objects.filter(oferente__matricula_de_trabajador__titulo__titulo__icontains=filtro_titulo)
    else:   
        ofertas_buscar=None
    cat=Categoria.objects.get(pk=id)
    ofertas = Oferta.objects.filter(categoria=cat.id)
    contexto = {"ofertas":ofertas,
                "search_form" : search_form}
    return render(request, "bolsa/index.html",contexto)

def borrar_oferta(request,id):
    oferta=Oferta.objects.get(pk=id)
    if oferta.oferente == request.user:
        if request.method == "POST":
            if oferta.oferente == request.user:
                oferta.delete()
                return redirect("index")            
        else:
            oferta.delete()
            return redirect("index")


def editar_oferta(request, id):
    oferta = Oferta.objects.get(pk = id)
    if oferta.oferente == request.user:
        if request.method == "GET":
            form = OfertaForm(instance = oferta)
            contexto = {
                "form" : form,
                "editar" : "editar"
            }
            return render(request, "bolsa/new.html", contexto)
        elif request.method == "POST":
            form = OfertaForm(request.POST,request.FILES, instance = oferta)
            if form.is_valid():
                datos=form.cleaned_data
                b=datetime.now()
                if datos["fecha_caducacion"]:
                    if datos["fecha_caducacion"] > b.date():
                        ofer = form.save()
                        return redirect("oferta", ofer.id)
                    else:
                        contexto={"form":form,"error_fecha":"La fecha es vieja"}
                        return render(request, "bolsa/new.html",contexto)
                else:
                    ofer = form.save()
                    return redirect("oferta", ofer.id)
                    
            else:
                contexto = {
                "form" : form,
                }
                return render(request, "bolsa/new.html", contexto)

bolsa/templates/bolsa/index.html
{% extends 'base.html' %}
{% load static %}
{%block titulo%}
 Inicio
{% endblock %}
{%block contenido%}
<main role="main">
    <div class="container">  
    	<div class="row">
        {% include 'bolsa/search_form.html'%}
      </div>
       <div class="row">
        <!--comienza--> 
        {% include 'bolsa/lista_oferta.html' with ofertas=ofertas_buscar %}
       <!--Termina-->
      </div>
      {{oferta1}}
      {% if ofertas1 %}
      <h2 class="text-white">En tu localidad:</h2>
      {% endif %}
      <div class="row">
        <!--comienza--> 
        {% include 'bolsa/lista_oferta.html' with ofertas=ofertas1 %}
       <!--Termina-->
      </div>
      <h2 class="text-white">Todas las ofertas:</h2>
      <div class="row">
        <!--comienza--> 
        {% include 'bolsa/lista_oferta.html' with ofertas=ofertas %}
       <!--Termina-->
      </div>
    </div>
   

</main>

{% endblock %}

bolsa/templates/bolsa/lista_oferta.html
{% load static %}
{% for oferta in ofertas %}          
<div class="col-xs-12 col-md-4 text-center">
  <div id="contenedor_oferta" class="card mb-4 shadow-sm">
    <span>{{oferta.titulo}}</span>
    <a href="{% url 'oferta' oferta.id %}">
      {% if oferta.imagen%}
      <img class="bd-placeholder-img card-img-top" width="100%" height="225" src=  
      "{{oferta.imagen.url}}" alt="imagen de oferta">
      {% elif oferta.oferente.foto %}
       <img class="bd-placeholder-img card-img-top" width="100%" height="225" src=  
      "{{oferta.oferente.foto.url}}" alt="imagen usuario">
      {% else %}
       <img class="bd-placeholder-img card-img-top" width="100%" height="225" src=  
      "{% static 'img/pordefecto.jpg' %}" alt="imagen por defecto">
      {% endif %} 
    </a>
    <div class="card-body">
      <p class="card-text text-white">{{oferta.descripcion | truncatechars:40}}</p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group d-flex ">
            <a href="{% url 'ver_perfil' oferta.oferente.id %}" class="btn btn-sm btn-outline-secondary text-white text-white">Perfil</a>
            <a href="{% url 'oferta' oferta.id %}" class="btn btn-sm btn-outline-secondary text-white">Oferta Completa</a>
        </div>
        <small id="fecha_cad" class="text-white">
          {% ifequal oferta.fecha_caducacion none %}
            No tiene fecha limite
          {% else %}
            {{oferta.fecha_caducacion}} 
          {% endifequal %} 
        </small>
        
      </div>
    </div>
  </div>
</div> 

{% endfor %}                

bolsa/templates/bolsa/new.html
{% extends 'base.html' %}

{% block headtitle %}
    Oferta
{% endblock %}

{%block contenido%}
<div class="contenedor-form">
     <div class="formulario">
        <h1 class="text-center">Oferta</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <br>
          <label for="id_titulo">Titulo</label>
            {{ form.titulo }}
            <div>
          <p>
            {{ form.titulo.errors }}
          </p>
        </div>

          <label for="id_descripcion">Descripcion</label>
            {{ form.descripcion }}
              <div>
          <p>
            {{ form.decripcion.errors }}
          </p>
        </div>
          <label for="id_oferente">Imagen</label>
            {{ form.imagen }}
        <label>Fecha de Caducidad</label>
                {{form.fecha_caducacion}}
            <div>
          <p>
            {{ form.fecha_caducacion.errors }}
            {% if error_fecha %}
              {{error_fecha}}
            {% endif %}
          </p>
        </div>
        
      {% ifequal editar "editar" %}
      <input type="submit" value="Confirmar Cambios">
    {% else %}
      <input type="submit" value="Crear Oferta">
    {% endifequal %}
      

    </form>
</div>
</div>
 
{%endblock%}

bolsa/templates/bolsa/oferta.html
{% extends 'base.html' %}
{% load static %}
{% block headtitle %}
    Oferta : {{oferta.titulo}}
{% endblock %}

{%block contenido%}
<div class="row justify-content-center">
        <div class="col-xs-12 col-md-4 col-lg-6 text-center">
          <div id="contenedor_oferta" class="card mb-4 lg-10 shadow-sm">
            <span><h2>{{oferta.titulo}}</h2></span>
            <p class="text-left">Creada el : {{oferta.fecha_creado}}</p>
            <span><h6 class="text-left">Creador: {{ oferta.oferente }}</h6></span>
             {% if oferta.imagen %}
             <img class="rounded img-fluid" width="350" height="250" src=  
            "{{oferta.imagen.url}}" alt="imagen de oferta">
            {% elif request.user.foto %}
            <img class="rounded img-fluid" width="250" height="150" src=  
            "{{oferta.oferente.foto.url}}" alt="imagen usuario">
            {% else %}
             <img class="rounded img-fluid" width="250" height="150" src=  
            "{% static 'img/pordefecto.jpg' %}" alt="imagen por defecto">
            {% endif %} 


            
            <div class="card-body">
              <h4>Oferta</h4>
              <p id="descripcion_oferta" class="text-left card-text text-white">{{oferta.descripcion}}</p>
              <div class="d-flex justify-content-between">
                <small class="text-white">
                La oferta termina: 
                  {% ifequal oferta.fecha_caducacion none %}
                    No tiene fecha limite
                  {% else %}
                    {{oferta.fecha_caducacion}} 
                  {% endifequal %}
                </small>
                <a class ="text-white" href="{% url 'ver_perfil' oferta.oferente.id %}">
                
                </a>
                <br>
                <a class ="text-white" href="{% url 'show_categoria' oferta.categoria.id %}">
                <span><h6>Categoria: {{ oferta.categoria }}</h6></span>
                </a>
              </div>
              <div class="row d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'ver_perfil' oferta.oferente.id %}" class="btn btn-sm btn-outline-secondary text-white text-white">Perfil</a>
                    {% if oferta.oferente == request.user %}
                    <a href="{% url 'editar_oferta' oferta.id %}" class="btn btn-sm btn-outline-secondary text-white text-white">Editar Oferta</a>
                    <a href="{% url 'borrar_oferta' oferta.id %}" class="btn btn-sm btn-outline-secondary text-white text-white">Borrar Oferta</a>
                    {% endif %}
                </div>
              </div>
            
          </div>
        </div> 
</div>           
{% endblock %}

bolsa/templates/bolsa/search_form.html
<div class="contenedor-form">
    <div class="formulario"> 
        <form method="GET">
            <label for="{{ search_form.titulo.id_for_label }}">Buscar:</label>
            {{ search_form.titulo }}
            <button class="btn waves-effect waves-light" type="submit">
                <i class="fa fa-search" aria-hidden="true">  Buscar</i>
            </button>         
        </form>
    </div>
</div>