bolsa/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
path("", views.index, name="index"),
path("oferta/<int:id>", views.show_oferta, name="oferta"),
path("oferta/new", views.new_oferta,name="new_oferta"),
path("oferta/categoria/<int:id>", views.show_categoria,name="show_categoria"),
path("oferta/<int:id>/borrar", views.borrar_oferta, name="borrar_oferta"),
path("oferta/<int:id>/editar", views.editar_oferta, name="editar_oferta"),
]

cuenta/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("iniciar_sesion", views.iniciar_sesion, name="iniciar_sesion"),
    path("cerrar_sesion", views.cerrar_sesion, name="cerrar_sesion"),
    path("nuevo_cliente", views.nuevo_cliente, name="nuevo_cliente"),
    path("nuevo_trabajador", views.nuevo_trabajador, name="nuevo_trabajador"),
    path("perfil/editar/cargar_titulo/<int:id>", views.cargar_titulo, name="cargar_titulo"),
    path("perfil/<int:id>", views.ver_perfil, name="ver_perfil"),
    path("perfil/editar/<int:id>", views.editar_perfil, name="editar_perfil"),
    path("perfil/editar/cambiar_pass/<int:id>", views.cambiar_pass, name="cambiar_pass"),
    path("perfil/editar/borrar_titulo/<int:id>", views.borrar_titulo, name="borrar_titulo"),
    path("perfil/si_recomiendo/<int:id>", views.si_recomiendo, name="si_recomiendo"),
    path("perfil/no_recomiendo/<int:id>", views.no_recomiendo, name="no_recomiendo"),
    path("perfil/<int:id>/comentar", views.comentar, name="comentar"),
    path("search_perfil/", views.search_perfil, name="search_perfil"),
    path("perfil/dar_baja/<int:id>", views.dar_baja, name="dar_baja"),
    path("perfil/dar_baja_definitiva/<int:id>", views.dar_baja_definitiva, name="dar_baja_definitiva"),
    path("ayuda", views.ayuda, name="ayuda"),
    ]

proyecto_etapa2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("bolsa.urls")),
    path("cuenta/", include("cuenta.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cuenta/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .validators import validar_num
# Create your models here.

class Provincia(models.Model):
    provincia = models.CharField(max_length = 30)
    def __str__(self):
        return self.provincia

class Localidad(models.Model):
    localidad = models.CharField(max_length = 30)
    provincia = models.ForeignKey(Provincia, on_delete = models.CASCADE,default=None, related_name="personas_provincia")
    def __str__(self):
        return self.provincia.provincia+" - "+self.localidad

class Categoria(models.Model):
    nombre_cat = models.CharField(max_length = 30)
    descripcion = models.TextField()
    def __str__(self):
        return self.nombre_cat

class Titulo(models.Model):
    titulo = models.CharField(max_length = 30)
    categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE,default=None, related_name="titulo_de_categoria")
    def __str__(self):
        return self.titulo

class Perfil(AbstractUser):
    tipo_usuario=models.CharField(max_length=20,default="cliente")
    dni=models.CharField(max_length=10,unique=True,default="",validators=[validar_num])
    nacimiento = models.DateField(null = True)
    foto = models.ImageField(upload_to = "foto_perfil", null = True, blank = True)
    telefono = models.CharField(max_length = 20,validators=[validar_num])
    localidad = models.ForeignKey(Localidad, on_delete = models.CASCADE, null=True, related_name="personas_localidad") 
    experiencia_laboral = models.CharField(max_length = 200,null = True, blank = True)
    categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE, default=None, null=True, related_name="perfil_de_categoria")
    facebook = models.CharField(max_length = 40, null=True)
    instagram = models.CharField(max_length = 40, null=True, blank = True)
    recomendaciones = models.ManyToManyField("Perfil", blank=True, through="Recomendaciones", related_name="trabajador_recomendado") 
    def __str__(self):
        return self.username

class Matricula_Titulo(models.Model):
    trabajador = models.ForeignKey(Perfil, on_delete = models.SET_NULL, null = True, related_name="matricula_de_trabajador")
    titulo = models.ForeignKey(Titulo, on_delete = models.CASCADE,null = True, related_name="matricula_de_titulo")
    matricula = models.CharField(max_length = 30,null = True, blank=True)
    class Meta:
        unique_together = ("trabajador","titulo")
    def __str__(self):
        return self.matricula

class Comentario(models.Model):
    com_trabajador = models.ForeignKey(Perfil, on_delete = models.CASCADE, related_name="comentarios_de_trabajador")
    usuario = models.ForeignKey(Perfil, on_delete = models.SET_NULL, null = True, related_name="comentario_cliente")
    texto = models.TextField(max_length = 200)
    fecha_creacion = models.DateTimeField(auto_now_add = True)

class Recomendaciones(models.Model):
    trabajador = models.ForeignKey(Perfil, on_delete = models.SET_NULL, null = True, related_name="recomendado")
    cliente = models.ForeignKey(Perfil, on_delete = models.SET_NULL, null = True, related_name="cliente_recomendante")
    recomendaciones = models.IntegerField(default=0, null = True, blank=True)
    class Meta:
        unique_together = ("trabajador","cliente")
    def __str__(self):
        return self.recomendaciones

class Que_hacemos(models.Model):
    que_es = models.TextField(max_length=300,default="")
    que_permite = models.TextField(max_length=300,default="")
    porque_nosotros = models.TextField(max_length=300,default="")

cuenta/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from .models import Perfil,Titulo,Localidad,Matricula_Titulo,Categoria,Comentario


class NuevoUsuarioForm(UserCreationForm,forms.Form):
    localidad=forms.ModelChoiceField(queryset=Localidad.objects.all().order_by("provincia__provincia","localidad"))
    username=forms.CharField(initial="", widget=forms.TextInput(attrs={"placeholder":"Nombre de usuario"}))
    dni=forms.IntegerField(max_value=99999999)
    first_name=forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Nombre"}))
    last_name=forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Apellido"}))
    email=forms.EmailField(initial="",widget=forms.TextInput(attrs={"placeholder":"Correo Electronico"}))
    password1=forms.CharField(max_length=32, widget=forms.PasswordInput)
    password2=forms.CharField(max_length=32, widget=forms.PasswordInput)
    nacimiento=forms.DateField(widget=forms.TextInput(attrs={"placeholder":"01/01/1000"}))
    foto=forms.ImageField(required=False)
    telefono= forms.CharField(help_text='Numero de Contacto', widget=forms.TextInput(attrs={"placeholder":"codigo numero"}))
    categoria=forms.ModelChoiceField(required=False, queryset=Categoria.objects.all(),initial="1")
    experiencia_laboral=forms.CharField(required=False, widget=forms.Textarea(attrs={"placeholder":"Tu forma de trabajar en 200 caracteres"}))
    facebook=forms.CharField(required=False)
    instagram=forms.CharField(required=False)
    class Meta:
        model = Perfil
        fields = ("first_name","last_name","username","dni", "email", "password1",
         "password2", "nacimiento", "foto","telefono","localidad","categoria",
         "experiencia_laboral","facebook","instagram")

class UpdateUsuarioForm(UserChangeForm):
    class Meta:
        model = Perfil
        fields = ("username","email","foto","telefono","experiencia_laboral","localidad","categoria","facebook","instagram")
    def __init__(self,*args, **kwargs):
        super(UpdateUsuarioForm, self).__init__(*args, **kwargs)
        localidad=forms.ModelChoiceField(queryset=Localidad.objects.all().order_by("localidad"))
        self.fields["localidad"]=localidad
        experiencia_laboral=forms.CharField(required=False,widget=forms.Textarea(attrs={"placeholder":"Tu forma de trabajar en 200 caracteres"}))
        self.fields["experiencia_laboral"]=experiencia_laboral
        facebook=forms.CharField(required=False)
        self.fields["facebook"]=facebook
        instagram=forms.CharField(required=False)
        self.fields["instagram"]=instagram

class TerminarInscripcionForm(forms.ModelForm):
    titulo_nuevo=forms.CharField(required=False, widget=forms.TextInput(attrs={"placeholder":"Ingrese su actividad"}))
    class Meta:
        model = Matricula_Titulo
        fields=("matricula","titulo", "titulo_nuevo")
    def __init__(self,categoria, *args, **kwargs):
        super(TerminarInscripcionForm, self).__init__(*args, **kwargs)
        titulo=forms.ModelChoiceField(queryset = Titulo.objects.filter(categoria_id = categoria),widget=forms.RadioSelect,required = False)
        self.fields["titulo"]=titulo

class ComentarioForm(forms.ModelForm):
    texto=forms.CharField(max_length=200, widget=forms.TextInput(attrs={"placeholder":"comentario"}))
    class Meta:
        model = Comentario
        fields =("texto",)

class Recuperar_passForm(forms.ModelForm):
    class Meta:
        fields= ("username","dni", "email", "nacimiento")

class Search_perfilForm(forms.Form):
    class Meta:
        model = Titulo
        fields =("titulo","localidad")
    def __init__(self, *args, **kwargs):
        super(Search_perfilForm, self).__init__(*args, **kwargs)
        titulo = forms.ModelChoiceField(queryset=Titulo.objects.all().order_by("titulo"), required = False)
        self.fields["titulo"]= titulo
        localidad=forms.ModelChoiceField(queryset=Localidad.objects.all().order_by("provincia__provincia","localidad"),required = False)
        self.fields["localidad"]= localidad

cuenta/templates/cuenta/cambiar_contrasena.html
{% extends 'base.html' %}
{% load static %}
{%block titulo%}
 Cambiar Contraseña
{% endblock %}
{%block contenido%}
<div class="contenedor-form">
    <br>
    <div class="formulario">
            <h2>Cambiar contraseña</h2>
            <form method="POST">
                {% csrf_token %}
                {{form}}
                {{form.errors}}
                <input type="submit" value="Cambiar contraseña">
            </form>
    </div>
{% endblock %}

cuenta/templates/cuenta/cargar_titulo.html
{% extends 'base.html' %}
{% load static %}
{%block titulo%}
Cargar Cuenta
{% endblock %}
{%block contenido%}
<div class="contenedor-form">
    <br>
    <div class="formulario">
            <h2 class="text-center">Cargar Titulo</h2>
      <form method="POST" enctype="multipart/form-data">
                 {% csrf_token %} 
      <label for="id_username">Oficio o Profesión</label>
      {%ifequal request.user.categoria.id 5 %}
        {{ form.titulo }}
        <div>
          <p>
            {{ form.titulo.errors }}
          </p>
        </div>
        {% if caso != "especial" %}
        {{ form.titulo_nuevo }}
        <div>
          <p>
            {{ form.titulo_nuevo.errors }}
          </p>
        </div>
        {% endif %}
      {% else %}

        {{ form.titulo }}
        <div>
          <p>
            {{ form.titulo.errors }}
          </p>
        </div>
       {% endifequal %}     
      <label for="id_email">Matricula (opcional)</label>
      {{ form.matricula }}
      <div>
        <p>
          {{ form.matricula.errors }}
        </p>
      </div>                       
            <input type="submit" value="Cargar Titulo">
      </form>
      <h2>{{error}}</h2>
    </div>
</div>
{% endblock %}

cuenta/templates/cuenta/crear_cuenta.html
{% extends 'base.html' %}
{% load static %}
{%block titulo%}
 Crear cuenta {{pagina}}
{% endblock %}
{%block contenido%}
<div class="row">
  <div class="col-md-6">
    <div class="contenedor-form">
      <div class="formulario">
        <br>
        {% ifequal pagina "cliente" %}
          <h2>Crea tu Cuenta Cliente</h2>
        {% else %}
          <h2>Crea tu Cuenta Trabajador</h2>
        {% endifequal %}
        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
          <label class="active" for="id_lastname">Nombre de Usuario</label>
          {{ form.username }}
          <p>
            {{ form.username.errors }}
          </p>
           <label class="active" for="id_firstname">DNI</label>
          {{ form.dni }}
          <div>
            <p>
              {{ form.dni.errors }}
            </p>
          </div>
          <label class="active" for="id_firstname">Nombre</label>
          {{ form.first_name }}
          <div>
            <p>
              {{ form.firs_name.errors }}
            </p>
          </div>               
          <label class="active" for="id_lastname">Apellido</label>
          {{ form.last_name }}
          <div>
            <p>
              {{ form.last_name.errors }}
            </p>
          </div>                
          <label class="active" for="id_email">Email</label>
          {{ form.email }}
          <div>
            <p>
              {{ form.email.errors }}
            </p>
          </div>                
          <label class="active" for="id_password1">Contraseña</label>
          {{ form.password1 }}
          <div>
            <p>
              {{ form.password1.errors }}
            </p>
          </div>                
          <label class="active" for="id_password2">Repetir Contraseña</label>
          {{ form.password2 }}
          <div>
            <p>
              {{ form.password2.errors }}
            </p>
          </div>
          <label class="active" for="id_nacimeinto">Fecha de Nacimiento</label>
          {{ form.nacimiento }}
          <div>
            <p>
              {{ form.nacimiento.errors }}
            </p>
          </div>              
          <label for="id_foto">foto</label>
          {{form.foto}}
          <div>
            <p>
              {{ form.foto.errors }}
            </p>
          </div>
          <label for="id_telefono">Telefono</label>
          {{form.telefono}}
          <div>
            <p>
              {{ form.telefono.errors }}
            </p>
          </div>
          <label for="id_facebook">Facebook(opcional)</label>
          {{form.facebook}}
          <div>
            <p>
              {{ form.facebook.errors }}
            </p>
          </div>
          <label for="id_instagram">Instagram(opcional)</label>
          {{form.instagram}}
          <div>
            <p>
              {{ form.instagram.errors }}
            </p>
          </div>
          <label for="id_localidad">Localidad</label>
          {{form.localidad}}
          <div>
            <p>
              {{ form.localidad.errors }}
            </p>
          </div>
          
            {% ifequal pagina "trabajador" %}
           <label for="id_experiencia_laboral">Experiencia Laboral</label>
          {{form.experiencia_laboral}}
          <div>
            <p>
              {{ form.experiencia_laboral.errors }}
            </p>
          </div>
          <label class="text-left" for="id_categoria">Categoria</label>
          {{form.categoria}}
          <div>
            <p>
              {{ form.categoria.errors }}
            </p>
          </div>
          {% endifequal %}
          <input type="submit" value="Registrarse">
        </form>
      </div>
    </div>
    </div>
</div>
{% ifequal pagina "trabajador" %}
<div class="row">
  <div id ="detalle" class="contenedor-form">
    <h3 class=text-center>Esta son las categorias</h3>
  {% for categoria in categorias %}
            <div>
              <h4>{{categoria.nombre_cat}}</h4>
          <p>
            {{categoria.descripcion}}
          </p>
        </div>
          {% endfor %}
  </div>
</div>
 {% endifequal %}
{% endblock %}
 {%block scripts%}
 <script src="{% static 'js/crear_cuenta.js' %}"></script>
  {%endblock%}

cuenta/templates/cuenta/dar_baja.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}
    Perfil de {{ perfil.username }}
{% endblock %}
{% block contenido%}
<div class="row justify-content-center">
    <div id="contenedor_perfil" class="container m-2">
        <div class="container m-2">
            <div class="row m-2">
                <div class="col-md-8">
                    {% if request.user.foto %}
                        <img src=  
                    "{{perfil.foto.url}}" width="60" height="60" class="float-left rounded-circle mr-2" alt="foto de perfil">
                    {%else%}
                        <img src="{% static 'img/pordefecto.jpg' %}" width="60" height="60" class="float-left rounded-circle" alt="logo">
                    {% endif %}
                    <h2 class="title">{{perfil.tipo_usuario|capfirst}}: {{perfil.username}}</h2>
                </div> 
            </div>

        
            <div class="row">
                <div class="">
                    <div class="card-body">
                        <h4 class="text-left">Datos Personales:</h4>
                        <h5 class="text-left">Nombre: {{perfil.first_name}}</h5>
                        <br>
                        <h5 class="text-left">Apellido: {{perfil.last_name}}</h5>
                        <br>
                        <h5 class="text-left">Telefono: {{perfil.telefono}}</h5>
                        <br>
                        <h5 class="text-left">Localidad : {{perfil.localidad}}</h5>      
                    </div>
                </div>

            {% ifequal request.user perfil %}
                <div class="contenedor-form">
                    <br>
                     <div class="formulario">
                        <form method="POST" action="{% url 'dar_baja_definitiva' perfil.id %}">
                            {% csrf_token %}
                            <input type="submit" value="Borrar Perfil">Desea Abandonar la Comunidad
                        </form>
                    </div>
                 </div>

            {% endifequal %}
        </div>
        <br>
    </div>
{% endblock %}

cuenta/templates/cuenta/editar_perfil.html
{% extends 'base.html' %}
{% load static %}
{%block titulo%}
Editar Perfil
{% endblock %}
{%block contenido%}
<div class="contenedor-form">
    <br>
    <div class="formulario">
            <h2>Editar Perfil</h2>
      <form method="POST" enctype="multipart/form-data">
                 {% csrf_token %}  
      <label for="id_username">Nombre de Usuario</label>
      {{ form.username }}
      <div>
        <p>
          {{ form.username.errors }}
        </p>
      </div>              
      <label for="id_email">Email</label>
      {{ form.email }}
      <div>
        <p>
          {{ form.email.errors }}
        </p>
      </div>                            
      <label for="id_foto">Foto</label>
      {{form.foto}}
      <div>
        <p>
          {{ form.foto.errors }}
        </p>
      </div>
      <label for="id_telefono">Telefono</label>
      {{form.telefono}}
      <div>
        <p>
          {{ form.telefono.errors }}
        </p>
      </div>
      <label for="id_facebook">Facebook(opcional)</label>
          {{form.facebook}}
          <div>
            <p>
              {{ form.facebook.errors }}
            </p>
          </div>
          <label for="id_instagram">Instagram(opcional)</label>
          {{form.instagram}}
          <div>
            <p>
              {{ form.instagram.errors }}
            </p>
          </div>
      <label for="id_localidad">Localidad</label>
      {{form.localidad}}
      <div>
        <p>
          {{ form.localidad.errors }}
        </p>
      </div>
      {% ifequal request.user.tipo_usuario "trabajador" %}

          <label id="label_titulo" for="id_titulo">Experiencia Laboral</label>
          {{ form.experiencia_laboral }}
         <div>
          <p>
            {{ form.experiencia_laboral.errors }}
          </p>
        </div>
        <label for="id_categoria">Categoria</label>
          {{ form.categoria }}
         <div>
          <p>
            {{ form.categoria.errors }}
          </p>
        </div>

      {% endifequal %}
                <input type="submit" value="Confirmar Cambios">
            </form>
    </div>
    <div class="reset-password">
        <a href="{% url 'cambiar_pass' request.user.id %}">Editar contraseña</a>
    </div>
</div>
</div>
{% endblock %}
 {%block scripts%}
  <script src="{% static 'js/crear_cuenta.js' %}"></script>
  {%endblock%}

cuenta/templates/cuenta/iniciar_sesion.html
{% extends 'base.html' %}
{% load static %}
{%block titulo%}
Iniciar Sesión
{% endblock %}
{%block contenido%}
<div class="container ">
    <div class="row justify-content-center">
    <div class="col-md-6">
<div class="contenedor-form">
    <br>
    <div class="formulario">
            <h2>Iniciar Sesión</h2>
            <form method="POST" action="#">
                 {% csrf_token %}
                <label class="active" for="id_lastname">Nombre de Usuario</label>
      {{ form.username }}
      <p>
        {{ form.username.errors }}
      </p>
       <label class="active" for="id_password">Contraseña</label>
      {{ form.password }}
      <div>
        <p>
          {{ form.password.errors }}
        </p>
      </div>                
                <input type="submit" value="Iniciar Sesión">
            </form>
    </div>
    </div>
    </div>
</div>
</div>
{% endblock %}

cuenta/templates/cuenta/perfil.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}
    Perfil de {{ perfil.username }}
{% endblock %}
{% block contenido%}
<div class="row justify-content-center">
    <div id="contenedor_perfil" class="container m-2">
        <div class="container m-2">
            <div class="row m-2">
                <div class="col-md-8">
                    {% if request.user.foto %}
                        <img src=  
                    "{{perfil.foto.url}}" width="60" height="60" class="float-left rounded-circle mr-2" alt="foto de perfil">
                    {%else%}
                        <img src="{% static 'img/pordefecto.jpg' %}" width="60" height="60" class="float-left rounded-circle" alt="logo">
                    {% endif %}
                    <h2 class="title">{{perfil.tipo_usuario|capfirst}}: {{perfil.username}}</h2>
                </div>
                <div class="col-md-4 mt-4">
                    {% ifequal request.user perfil %}
                        {% ifequal request.user.tipo_usuario "trabajador" %}
                        <a href="{% url 'new_oferta' %}" class="btn btn-lg btn-outline-secondary text-white"><strong><i class="fa fa-address-card" aria-hidden="true"></i> Oferta tu trabajo</strong></a>
                        {% endifequal %}
                    {% endifequal %}
                </div>
                
            </div>

        
            <div class="row">
                <div class="">
                    <div class="card-body">
                        <h4 class="text-left">Datos Personales:</h4>
                        <h5 class="text-left">Nombre: {{perfil.first_name}}</h5>
                        <br>
                        <h5 class="text-left">Apellido: {{perfil.last_name}}</h5>
                        <br>
                        <h5 class="text-left">Telefono: {{perfil.telefono}}</h5>
                        <br>
                        <h5 class="text-left">Localidad : {{perfil.localidad}}</h5>      
                    </div>
                </div>
            {% if perfil.tipo_usuario == "trabajador" %}
                <div class="col-md-8 ml-auto">
                    <div class="card-body"> 
                        <h4 class="text-white">Profesión:</h4>
                        <div class="container">
                            <div class="row">
                                {% for matricula in matriculas %}
                                    <div class="col-md-4 m-2">
                                    <h5 class="text-white">{{matricula.titulo}}</h5>
                                    {% if matricula.matricula != "" %}
                                    <h5 class="text-white">Matricula:{{matricula}}</h5>
                                    {% endif %}
                                    {% ifequal request.user perfil %}    
                                        <a href="{% url 'borrar_titulo'  matricula.id %}" class="btn btn-sm btn-outline-secondary text-white"><i class="fa fa-trash-o" aria-hidden="true"><strong> Borrar</strong></i></a>
                                    {% endifequal %} 
                                    </div>
                                {%endfor%}
                            </div>
                        </div>
                    </div> 
                </div>  


                </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Experiencia Laboral:</h4>
                        </div>
                        <div class="col-md-12">
                            <p id="descripcion_oferta" class="card-text text-white text-align">{{perfil.experiencia_laboral}}</p>
                        </div>
                    </div>
                </div>
           {% endif %} 
        <div class="container m-2 mt-4">
            <div class="row">
                <div class="col-md-4">
                    <div class="card-body">
                        <!--recomendaciones-->
                        <h6 class="text-left">Recomendaciones : {{recomendaciones}}</h6>
                        <a class="mr-4 text-white" href="{% url 'si_recomiendo' perfil.id %}"><i class="fa fa-thumbs-o-up fa-lg" aria-hidden="true"></i></a>
                        <a class="text-white" href="{% url 'no_recomiendo' perfil.id %}"><i class="fa fa-thumbs-o-down fa-lg" aria-hidden="true"></i></a>
                    </div>
                </div>

                <div class="col-md-4">
                    {% if perfil.tipo_usuario == "trabajador" %}
                    <h6>Contacta a tu profesional: </h6>
                    {% else %}
                    <h6 class="text-center">Contacta:</h6>
                    {% endif %}
                    <div class="card-body">
                         <a href="http://www.facebook.com/{{perfil.facebook}}" target="blank"><img width="30" height="30" class="float-left rounded-circle mr-2" src="{% static 'img/facebook.png' %}"></a>
                        <a href="http://www.instagram.com/{{perfil.instagram}}" target="blank"><img width="30" height="30" class="float-left rounded-circle mr-2" src="{% static 'img/instagram.jpg' %}"></a>
                        <a href="https://wa.me/{{perfil.telefono}}" target="blank"><img width="30" height="30" class="float-left rounded-circle mr-2" src="{% static 'img/whatsapp.png' %}"></a>
                    </div>
                </div>
                <div class="col-md-4">
                <div class="card-body">
                    <div class="btn-group">
                        {% ifequal request.user perfil %}
                            <a href="{% url 'editar_perfil' perfil.id %}" class="btn btn-md btn-outline-secondary text-white">Editar</a>
                             <a href="{% url 'dar_baja' perfil.id %}" class="btn btn-md btn-outline-secondary text-white"><i class="fa fa-trash-o" aria-hidden="true">Borrar Perfil</i></a>
                            {% ifequal request.user.tipo_usuario "trabajador" %}
                                <a href="{% url 'cargar_titulo' perfil.id %}" class="btn btn-md btn-outline-secondary text-white">Profesión</a>
                            {% endifequal %}
                        {% endifequal %}
                    </div>
                </div>
                </div>
            </div>


        </div>
        <br>
    </div> 
     
    <!--Comentarios-->
        {% if request.user.is_authenticated %}
            <div class="contenedor-form m-2 container">
                <div class="formulario"> 
                    <form method="POST" action="{% url 'comentar' perfil.id %}">
                        {% csrf_token %}
                        <div class="container m-2">
                            <label for="id_text"><h6>Comentario:</h6></label>
                            {{ form_comentario.texto }}
                          <button class="" type="submit" name="action">
                              <i class="fa fa-plus-circle" aria-hidden="true"></i>Agregar
                          </button>
                        </div>
                    </form>
                </div>
            </div>
        {% endif %}
        <div id="contenedor_perfil" class="container">
            <div class="container m-2">
                <div class="row">
                    <ul class="collection">
                        {% for comentario in comentarios %} 
                            <li class="">
                                {% if comentario.usuario.id %}
                                <a href="{% url 'ver_perfil' comentario.usuario.id %}">  
                                    {% if comentario.usuario.foto %}
                                        <img src="{{ comentario.usuario.foto.url }}" alt="foto de perfil" width="30" height="30" class="float-left rounded-circle mr-2">
                                    {% else %}
                                        <img src="{% static 'img/pordefecto.jpg' %}"  width="30" height="30" class="float-left rounded-circle mr-2" alt="archivo por defecto">
                                    {% endif %}
                                 </a>   
                                <a href="{% url 'ver_perfil' comentario.usuario.id %}">
                                <span class="title">{{comentario.usuario.username}}:</span>
                                </a>
                                {% else %}
                                <img src="{% static 'img/pordefecto.jpg' %}" width="30" height="30" class="float-left rounded-circle mr-2" alt="logo">
                                <h6>Cuenta Borrada</h6>
                                {% endif %}
                                <p class="text-align text-white"> 
                                    {{comentario.texto}}
                                </p>
                                <p>
                                    {{comentario.fecha_creacion}}
                                </p>
                                
                            </li>
                        {% endfor%}
                    </ul>
                </div>
            </div>
        </div>

</div>
    <!--Oferta del perfil-->
    <div class="container">  
      <div class="row">
        {% include 'bolsa/lista_oferta.html' with ofertas=ofertas %}
    </div>


{% endblock %}

cuenta/templates/cuenta/que_hacemos.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}
    Ayuda
{% endblock %}
{% block contenido%}
<div class="row justify-content-center">
    <div id="contenedor_perfil" class="container m-2">
        <h2 class="text-white text-center">¿Que es?</h2>
        <h3 class="text-white text-center">{{contenido.que_es}}</h3>
        <br>
        <br>
        <h2 class="text-white text-center">¿Que permite?</h2>
        <h3 class="text-white text-center">{{contenido.que_permite}}</h3>
        <br>
        <br>
        <h2 class="text-white text-center">Te ofrecemos:</h2>
        <h3 class="text-white text-center">{{contenido.porque_nosotros}}</h3>
    </div>
</div> 
{% endblock %}